In [162]:
import pandas as pd

In [163]:
df = pd.read_excel("D:\Graduation Project\Customers.xlsx")

In [164]:
df.head(10)

,CustomerID,Customer First Name,Customer Last Name,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid
0,SC-20575,Sayban,Abunfis,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261
1,KW-16570,Diea,Turkmany,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851
2,DP-13000,Jawaher,Alrz,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248
3,TB-21250,Katy,Muhamad,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641
4,PK-18910,Ali,Alkhayran,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504
5,JK-15625,Lama,Alnasar,Female,549433232,Egypt,lamaalnasar@email.com,2021-05-31,Jeddah,Mecca,V1,9766.908595
6,HE-14800,Muhamad,Husu,Male,565067284,Egypt,muhamadhusu@email.com,2021-01-30,Ad Diriyah,Riyadh,V1,31140.008040
7,JE-15610,Husam,Sydu,Male,544607887,Saudi Arabia,husamsydu@email.com,2021-10-06,Riyadh,Riyadh,V1,25832.107194
8,TB-21055,Shahad,Alajw,Female,552293702,Saudi Arabia,shahadalajw@email.com,2021-01-14,As Sulayyil,Riyadh,V1,52053.125046
9,DW-13195,Hazim,Alhusayn,Male,509271316,Egypt,hazimalhusayn@email.com,2021-01-19,Ad Diriyah,Riyadh,V2,5164.415724

In [165]:
df.describe(include='all')

,CustomerID,Customer First Name,Customer Last Name,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid
count,1577,1577,1577,1577,1.577000e+03,1577,1577,1577,1577,1577,1577,1577.000000
unique,1577,271,533,2,NaN,6,1577,NaN,93,13,4,NaN
top,SC-20575,Muhamad,Almisri,Male,NaN,Saudi Arabia,saybanabunfis@email.com,NaN,Riyadh,Riyadh,V1,NaN
freq,1,266,16,1046,NaN,651,1,NaN,214,381,915,NaN
mean,NaN,NaN,NaN,NaN,5.491275e+08,NaN,NaN,2021-08-12 15:24:05.022193920,NaN,NaN,NaN,19903.836785
min,NaN,NaN,NaN,NaN,5.000075e+08,NaN,NaN,2021-01-01 00:00:00,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,5.234763e+08,NaN,NaN,2021-03-09 00:00:00,NaN,NaN,NaN,1789.699200
50%,NaN,NaN,NaN,NaN,5.490596e+08,NaN,NaN,2021-06-03 00:00:00,NaN,NaN,NaN,8046.694080
75%,NaN,NaN,NaN,NaN,5.741345e+08,NaN,NaN,2021-10-11 00:00:00,NaN,NaN,NaN,31806.867240
max,NaN,NaN,NaN,NaN,5.999595e+08,NaN,NaN,2024-07-26 00:00:00,NaN,NaN,NaN,150261.219578
std,NaN,NaN,NaN,NaN,2.879076e+07,NaN,NaN,NaN,NaN,NaN,NaN,25154.233987

In [166]:
df.isnull().sum()

CustomerID             0
Customer First Name    0
Customer Last Name     0
Gender                 0
Phone Number           0
Nationality            0
Email Address          0
Start Deal             0
City                   0
Province               0
Level                  0
Paid                   0
dtype: int64

In [167]:
df['Customer Name'] =df['Customer First Name'] +" "+df['Customer Last Name']

In [168]:
df.columns

Index(['CustomerID', 'Customer First Name', 'Customer Last Name', 'Gender',
       'Phone Number', 'Nationality', 'Email Address', 'Start Deal', 'City',
       'Province', 'Level', 'Paid', 'Customer Name'],
      dtype='object')

In [169]:
df

,CustomerID,Customer First Name,Customer Last Name,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid,Customer Name
0,SC-20575,Sayban,Abunfis,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis
1,KW-16570,Diea,Turkmany,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany
2,DP-13000,Jawaher,Alrz,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz
3,TB-21250,Katy,Muhamad,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad
4,PK-18910,Ali,Alkhayran,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1572,MG-7875,Samir,Musur,Male,535858463,Saudi Arabia,samirmusur@email.com,2023-11-23,Al-Aflaj,Riyadh,V2,46.484800,Samir Musur
1573,CS-2490,Rasha,Almala,Female,576101048,Saudi Arabia,rashaalmala@email.com,2022-01-22,Al Makhwah,Al Bahah,V3,901.816800,Rasha Almala
1574,TN-11040,Muhamad,Zayd,Male,513000231,Saudi Arabia,muhamadzayd@email.com,2022-11-22,Al-Aflaj,Riyadh,V1,110.287700,Muhamad Zayd
1575,RA-9915,Ayham,Alghan,Male,566828033,Syria,ayhamalghan@email.com,2023-05-23,Badr Al Janoub,Najran,V1,167.102400,Ayham Alghan
1576,ME-8010,Lina,Alrrashid,Female,540909917,Syria,linaalrrashid@email.com,2023-12-04,Hajrah,Al Bahah,V1,483.429000,Lina Alrrashid

In [170]:
df.drop(columns=['Customer First Name','Customer Last Name'], inplace=True)

In [171]:
df

,CustomerID,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid,Customer Name
0,SC-20575,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis
1,KW-16570,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany
2,DP-13000,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz
3,TB-21250,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad
4,PK-18910,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran
...,...,...,...,...,...,...,...,...,...,...,...
1572,MG-7875,Male,535858463,Saudi Arabia,samirmusur@email.com,2023-11-23,Al-Aflaj,Riyadh,V2,46.484800,Samir Musur
1573,CS-2490,Female,576101048,Saudi Arabia,rashaalmala@email.com,2022-01-22,Al Makhwah,Al Bahah,V3,901.816800,Rasha Almala
1574,TN-11040,Male,513000231,Saudi Arabia,muhamadzayd@email.com,2022-11-22,Al-Aflaj,Riyadh,V1,110.287700,Muhamad Zayd
1575,RA-9915,Male,566828033,Syria,ayhamalghan@email.com,2023-05-23,Badr Al Janoub,Najran,V1,167.102400,Ayham Alghan
1576,ME-8010,Female,540909917,Syria,linaalrrashid@email.com,2023-12-04,Hajrah,Al Bahah,V1,483.429000,Lina Alrrashid

In [172]:
def Paid_Status(row):
    if row['Paid']>0:
        return"Paid"
    else:
        return"Not Paid"
df['Paid_Status']=df.apply(Paid_Status,axis=1)
df

,CustomerID,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid,Customer Name,Paid_Status
0,SC-20575,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis,Paid
1,KW-16570,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany,Paid
2,DP-13000,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz,Paid
3,TB-21250,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad,Paid
4,PK-18910,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...
1572,MG-7875,Male,535858463,Saudi Arabia,samirmusur@email.com,2023-11-23,Al-Aflaj,Riyadh,V2,46.484800,Samir Musur,Paid
1573,CS-2490,Female,576101048,Saudi Arabia,rashaalmala@email.com,2022-01-22,Al Makhwah,Al Bahah,V3,901.816800,Rasha Almala,Paid
1574,TN-11040,Male,513000231,Saudi Arabia,muhamadzayd@email.com,2022-11-22,Al-Aflaj,Riyadh,V1,110.287700,Muhamad Zayd,Paid
1575,RA-9915,Male,566828033,Syria,ayhamalghan@email.com,2023-05-23,Badr Al Janoub,Najran,V1,167.102400,Ayham Alghan,Paid
1576,ME-8010,Female,540909917,Syria,linaalrrashid@email.com,2023-12-04,Hajrah,Al Bahah,V1,483.429000,Lina Alrrashid,Paid

In [173]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\alasad\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\alasad\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\alasad\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\alasad\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [174]:
from sqlalchemy import create_engine
import pandas as pd

server = r'DESKTOP-0ETJ1HK\SQLEXPRESS'
database = 'Grad.Project'
driver = 'ODBC Driver 18 for SQL Server'

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver.replace(' ', '+')}&trusted_connection=yes&TrustServerCertificate=yes"
)

In [175]:
pd.read_sql("SELECT GETDATE()", engine)

C:\Users\ALasad\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

0 2026-03-16 22:49:42.200

In [176]:
table_name = "Customers_Data"
df.to_sql(table_name, engine, if_exists="replace", index=False)

11

In [177]:
pd.read_sql("SELECT TOP 5 * FROM Customers_Data", engine)

,CustomerID,Gender,Phone Number,Nationality,Email Address,Start Deal,City,Province,Level,Paid,Customer Name,Paid_Status
0,SC-20575,Female,516000352,Saudi Arabia,saybanabunfis@email.com,2021-05-21,Riyadh,Riyadh,V1,10519.917261,Sayban Abunfis,Paid
1,KW-16570,Male,553319849,Saudi Arabia,dieaturkmany@email.com,2021-02-08,Al Qassim,Al Qassim,V1,26212.289851,Diea Turkmany,Paid
2,DP-13000,Female,511700595,United Arab Emirates,jawaheralrz@email.com,2021-01-04,Jeddah,Mecca,V2,62163.334248,Jawaher Alrz,Paid
3,TB-21250,Female,586073003,Saudi Arabia,katymuhamad@email.com,2021-08-25,Jazan,Jizan,V1,6793.911641,Katy Muhamad,Paid
4,PK-18910,Male,528335918,Egypt,alialkhayran@email.com,2021-04-04,Jazan,Jizan,V1,14621.603504,Ali Alkhayran,Paid

Orders Table

In [178]:
df = pd.read_csv("D:\Graduation Project\Orders.csv")

In [179]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,NaN
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,NaN
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,NaN,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.4,Medium,NaN,Completed

In [180]:
df.describe(include='all')

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
count,50860,50860,50860,50860,50860,50860,50860,50860,50860,50860,...,50860,50860,50860.000000,50860.000000,50860.000000,50860.000000,50856,50860,33442.000000,32298
unique,25234,1429,1463,2,4,1573,1492,3,93,13,...,10281,3788,NaN,NaN,NaN,NaN,10020,4,NaN,3
top,DR-2024-100111,18/6/2024,22/11/2024,Internal,Standard Class,PO-18850,Muhamad Almisri,Consumer,Riyadh,Riyadh,...,OFF-AR-10003651,Staples,NaN,NaN,NaN,NaN,0.71,Medium,NaN,Completed
freq,14,133,130,46729,30502,97,169,26306,10939,17225,...,35,225,NaN,NaN,NaN,NaN,75,29213,NaN,29849
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,246.639063,3.477861,0.142742,28.601154,NaN,NaN,4.000030,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,488.047913,2.276957,0.212137,174.602732,NaN,NaN,1.119314,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,NaN,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,30.741750,2.000000,0.000000,0.000000,NaN,NaN,4.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,85.056000,3.000000,0.000000,9.240000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,251.197450,5.000000,0.200000,36.810000,NaN,NaN,5.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,NaN,NaN,5.000000,NaN

In [181]:
df.isnull().sum()

Order ID                 0
Order Date               0
Ship Date                0
Internal/External        0
Ship Mode                0
Customer ID              0
Customer Name            0
Segment                  0
City                     0
Provice                  0
Market                   0
Product ID               0
Product Name             0
Sales                    0
Quantity                 0
Discount                 0
Profit                   0
Shipping Cost            4
Order Priority           0
Rating               17418
Status               18562
dtype: int64

In [182]:
df['Shipping Cost'].max()

TypeError: '>=' not supported between instances of 'str' and 'float'

In [183]:
df.dtypes

Order ID              object
Order Date            object
Ship Date             object
Internal/External     object
Ship Mode             object
Customer ID           object
Customer Name         object
Segment               object
City                  object
Provice               object
Market                object
Product ID            object
Product Name          object
Sales                float64
Quantity               int64
Discount             float64
Profit               float64
Shipping Cost         object
Order Priority        object
Rating               float64
Status                object
dtype: object

In [184]:
df['Shipping Cost'] = pd.to_numeric(df['Shipping Cost'], errors='coerce')

In [185]:
df.dtypes

Order ID              object
Order Date            object
Ship Date             object
Internal/External     object
Ship Mode             object
Customer ID           object
Customer Name         object
Segment               object
City                  object
Provice               object
Market                object
Product ID            object
Product Name          object
Sales                float64
Quantity               int64
Discount             float64
Profit               float64
Shipping Cost        float64
Order Priority        object
Rating               float64
Status                object
dtype: object

In [186]:
df['Shipping Cost'].max()

987.41

In [187]:
df['Shipping Cost'].min()

0.0

In [188]:
df['Shipping Cost'].mode()

0    0.71
Name: Shipping Cost, dtype: float64

In [189]:
df['Shipping Cost'].sample()

46729    14.54
Name: Shipping Cost, dtype: float64

In [190]:
df['Shipping Cost'].fillna(df['Shipping Cost'].mean(),inplace=True)

C:\Users\ALasad\AppData\Local\Temp\ipykernel_23508\2249583818.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Shipping Cost'].fillna(df['Shipping Cost'].mean(),inplace=True)

In [191]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,NaN
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,NaN
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,NaN,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium,NaN,Completed

In [192]:
df['Rating'].mode()

0    5.0
Name: Rating, dtype: float64

In [193]:
df['Rating'].max()

5.0

In [194]:
df['Rating'].min()

1.0

In [195]:
df['Rating'].fillna(df['Rating'].median(),inplace=True)

C:\Users\ALasad\AppData\Local\Temp\ipykernel_23508\822450396.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].median(),inplace=True)

In [196]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,NaN
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,NaN
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,4.0,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium,4.0,Completed

In [197]:
df['Status'].fillna("Pending",inplace=True)

C:\Users\ALasad\AppData\Local\Temp\ipykernel_23508\334487746.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Status'].fillna("Pending",inplace=True)

In [198]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,Pending
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,Pending
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,4.0,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium,4.0,Completed

In [199]:
df.isnull().sum()

Order ID             0
Order Date           0
Ship Date            0
Internal/External    0
Ship Mode            0
Customer ID          0
Customer Name        0
Segment              0
City                 0
Provice              0
Market               0
Product ID           0
Product Name         0
Sales                0
Quantity             0
Discount             0
Profit               0
Shipping Cost        0
Order Priority       0
Rating               0
Status               0
dtype: int64

In [200]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,Pending
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,Pending
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,4.0,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium,4.0,Completed

In [201]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,Pending
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,Pending
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,4.0,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium,4.0,Completed

In [203]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Product ID,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,OFF-LA-10002782,"Hon File Folder Labels, Adjustable",13.08,3,0.0,4.56,1.03,Medium,4.0,Pending
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-FU-10004015,"Tenex Clock, Durable",252.16,8,0.0,90.72,13.45,Medium,5.0,Completed
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,FUR-BO-10002352,"Ikea 3-Shelf Cabinet, Mobile",193.28,2,0.0,54.08,9.63,Medium,4.0,Completed
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-BI-10004428,"Cardinal Binder, Clear",35.44,4,0.0,4.96,1.37,Medium,5.0,Pending
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,OFF-AR-10004594,"Sanford Canvas, Water Color",71.60,2,0.0,11.44,3.79,Medium,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-AVE-10004570,"Avery Binder Covers, Economy",11.07,1,0.0,3.42,1.98,High,4.0,Completed
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,TEC-LOG-10004419,"Logitech Flash Drive, USB",61.44,2,0.0,18.42,13.02,High,4.0,Completed
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-BOS-10002705,"Boston Highlighters, Fluorescent",80.52,4,0.0,20.88,8.78,High,5.0,Completed
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,OFF-ENE-10004132,"Enermax Computer Printout Paper, 8.5 x 11",130.44,4,0.0,33.84,18.97,High,2.0,Completed
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,OFF-ACC-10002343,"Acco 3-Hole Punch, Durable",31.62,1,0.0,12.96,2.40,Medium,4.0,Completed

In [213]:
df['Discount'].sample()

21264    0.17
Name: Discount, dtype: float64

In [214]:
df['Net Profit.B']=df['Profit']-df['Shipping Cost']

In [215]:
df['Net Profit.A']=df['Net Profit.B']-(df['Net Profit.B']*df['Discount'])

In [216]:
df

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status,Net Profit.B,Net Profit.A
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,13.08,3,0.0,4.56,1.03,Medium,4.0,Pending,3.53,3.53
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,252.16,8,0.0,90.72,13.45,Medium,5.0,Completed,77.27,77.27
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,193.28,2,0.0,54.08,9.63,Medium,4.0,Completed,44.45,44.45
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,35.44,4,0.0,4.96,1.37,Medium,5.0,Pending,3.59,3.59
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,71.60,2,0.0,11.44,3.79,Medium,4.0,Completed,7.65,7.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50855,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,11.07,1,0.0,3.42,1.98,High,4.0,Completed,1.44,1.44
50856,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,61.44,2,0.0,18.42,13.02,High,4.0,Completed,5.40,5.40
50857,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,80.52,4,0.0,20.88,8.78,High,5.0,Completed,12.10,12.10
50858,SK-2022-7730,5/9/2022,7/9/2022,Internal,First Class,NF-8385,Amyrah Tutwnji,Consumer,Sakaka,Al Jouf,...,130.44,4,0.0,33.84,18.97,High,2.0,Completed,14.87,14.87
50859,AQ-2021-5750,25/8/2021,29/8/2021,Internal,Standard Class,SZ-10035,Mahir Eubdallah,Home Office,Al Aqiq,Al Bahah,...,31.62,1,0.0,12.96,2.40,Medium,4.0,Completed,10.56,10.56

In [217]:
df.head(20)

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status,Net Profit.B,Net Profit.A
0,RY-2024-143658,2/10/2024,6/10/2024,Internal,Standard Class,SC-20575,Sayban Abunfis,Consumer,Riyadh,Riyadh,...,13.080,3,0.0,4.560,1.03,Medium,4.0,Pending,3.530,3.5300
1,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,252.160,8,0.0,90.720,13.45,Medium,5.0,Completed,77.270,77.2700
2,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,193.280,2,0.0,54.080,9.63,Medium,4.0,Completed,44.450,44.4500
3,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,35.440,4,0.0,4.960,1.37,Medium,5.0,Pending,3.590,3.5900
4,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,71.600,2,0.0,11.440,3.79,Medium,4.0,Completed,7.650,7.6500
5,QS-2022-155047,15/10/2022,20/10/2022,Internal,Standard Class,KW-16570,Diea Turkmany,Consumer,Al Qassim,Al Qassim,...,56.120,2,0.0,21.320,4.72,Medium,4.0,Completed,16.600,16.6000
6,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,56.120,2,0.0,21.320,4.11,Medium,4.0,Completed,17.210,17.2100
7,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,344.640,3,0.0,165.420,26.20,Medium,4.0,Completed,139.220,139.2200
8,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,97.360,4,0.0,19.440,6.86,Medium,4.0,Pending,12.580,12.5800
9,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,341.520,2,0.0,13.640,17.34,Medium,4.0,Returned,-3.700,-3.7000
10,JD-2023-134096,27/9/2023,1/10/2023,Internal,Standard Class,DP-13000,Jawaher Alrz,Consumer,Jeddah,Mecca,...,12.060,3,0.0,3.480,1.13,Medium,4.0,Pending,2.350,2.3500
11,JZ-2023-156335,5/3/2023,12/3/2023,Internal,Standard Class,TB-21250,Katy Muhamad,Consumer,Jazan,Jizan,...,20.760,3,0.0,9.540,0.65,Medium,5.0,Completed,8.890,8.8900
12,JZ-2023-156335,5/3/2023,12/3/2023,Internal,Standard Class,TB-21250,Katy Muhamad,Consumer,Jazan,Jizan,...,210.640,4,0.0,50.480,16.07,Medium,4.0,Pending,34.410,34.4100
13,JZ-2024-121923,24/9/2024,1/10/2024,Internal,Standard Class,PK-18910,Ali Alkhayran,Home Office,Jazan,Jizan,...,80.100,3,0.0,37.620,8.86,Low,4.0,Completed,28.760,28.7600
14,JD-2024-135706,18/10/2024,23/10/2024,Internal,Standard Class,JK-15625,Lama Alnasar,Consumer,Jeddah,Mecca,...,132.640,4,0.0,35.760,6.20,Medium,3.0,Pending,29.560,29.5600
15,JD-2024-135706,18/10/2024,23/10/2024,Internal,Standard Class,JK-15625,Lama Alnasar,Consumer,Jeddah,Mecca,...,12.940,1,0.0,1.020,0.46,Medium,4.0,Pending,0.560,0.5600
16,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,18.840,2,0.4,-6.600,1.60,Medium,4.0,Pending,-8.200,-4.9200
17,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,308.280,7,0.4,-149.100,27.77,Medium,4.0,Pending,-176.870,-106.1220
18,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,40.176,2,0.4,-6.064,2.14,Medium,4.0,Pending,-8.204,-4.9224
19,DR-2023-126655,26/6/2023,1/7/2023,Internal,Standard Class,HE-14800,Muhamad Husu,Corporate,Ad Diriyah,Riyadh,...,8.784,3,0.4,-4.836,0.38,Medium,5.0,Completed,-5.216,-3.1296

In [218]:
from sqlalchemy import create_engine
import pandas as pd

server = r'DESKTOP-0ETJ1HK\SQLEXPRESS'
database = 'Grad.Project'
driver = 'ODBC Driver 18 for SQL Server'

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver.replace(' ', '+')}&trusted_connection=yes&TrustServerCertificate=yes"
)

In [219]:
table_name = "Orders_Data"
df.to_sql(table_name, engine, if_exists="replace", index=False)

C:\Users\ALasad\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

82

In [221]:
pd.read_sql("SELECT TOP 5 * FROM Orders_Data", engine)

,Order ID,Order Date,Ship Date,Internal/External,Ship Mode,Customer ID,Customer Name,Segment,City,Provice,...,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Rating,Status,Net Profit.B,Net Profit.A
0,DR-2021-2660642,10/5/2021,12/5/2021,Internal,Second Class,ML-18040,Muhamad Alkhalid,Corporate,Ad Diriyah,Riyadh,...,39.06,4,0.5,-17.22,12.78,Critical,4.0,Pending,-30.00,-15.000
1,DR-2021-2660642,10/5/2021,12/5/2021,Internal,Second Class,ML-18040,Muhamad Alkhalid,Corporate,Ad Diriyah,Riyadh,...,43.83,3,0.5,-32.49,13.98,Critical,4.0,Completed,-46.47,-23.235
2,DR-2021-2660642,10/5/2021,12/5/2021,Internal,Second Class,ML-18040,Muhamad Alkhalid,Corporate,Ad Diriyah,Riyadh,...,609.66,6,0.5,-231.84,71.32,Critical,4.0,Completed,-303.16,-151.580
3,AS-2022-5141433,6/3/2022,8/3/2022,Internal,First Class,AG-10390,Thayir Rinkusi,Consumer,Aseer,Aseer,...,15.48,2,0.5,-6.84,3.78,Critical,4.0,Completed,-10.62,-5.310
4,AS-2022-5141433,6/3/2022,8/3/2022,Internal,First Class,AG-10390,Thayir Rinkusi,Consumer,Aseer,Aseer,...,47.61,2,0.5,-29.55,13.58,Critical,4.0,Completed,-43.13,-21.565